# NumPy Exercises 4 Fun

Let's keep building on our basic numpy skills with the exercises below. If possible, use the numpy functions instead of native python code. 

In [3]:
import numpy as np
np.random.seed(42) # This guarantees the code will generate the same set of random numbers whenever executed

## Exercise 1

Let's create two matrices

In [4]:
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(first_matrix)

[[1 2 3]
 [4 5 6]]


In [5]:
second_matrix = np.array([1, 2, 3])
print(second_matrix)

[1 2 3]


Task 1: without running any code, write down on a piece of paper your prediction for the result from the following operation:

<b>first_matrix+second_matrix</b>

DO NOT CHEAT!

Task 2. Now execute the statement above and check your prediction.

In [6]:
print(first_matrix+second_matrix)

[[2 4 6]
 [5 7 9]]


prediction was right


## Exercise 2

Let's create a common array to work with:

In [7]:
np.random.seed(42) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=15, size=(3, 5))
random_integers

array([[ 7,  4, 13, 11,  8],
       [13,  5,  7, 10,  3],
       [ 7, 11, 11,  8,  5]])

Compute:

1. The average value of the entries in the second column
2. The maximum value in the second row
3. The minimum value in the third row
4. The location of the smallest value in the array


In [8]:
np.average(random_integers[:,1])

6.666666666666667

In [9]:
np.max(random_integers[1,:])

13

In [10]:
np.min(random_integers[2,:])

5

In [11]:
np.argmin(random_integers)

9

In [12]:
ind = np.unravel_index(np.argmin(random_integers, axis=None), random_integers.shape)
print(ind)

(1, 4)


## Exercise 3

Use the 3x5 array from the previous exercise.

1. Delete the third column and print the resulting 3x4 array
2. Now insert the following data [1,2,3] in place of the deleted third column and print the resulting 3x5 array 


In [13]:
a=np.delete(random_integers,3,1)
print(a)

[[ 7  4 13  8]
 [13  5  7  3]
 [ 7 11 11  5]]


In [14]:
b=np.insert(arr=a,axis=1,values=[1,2,3],obj=3)
print(b)

[[ 7  4 13  1  8]
 [13  5  7  2  3]
 [ 7 11 11  3  5]]


## Exercise 4. 

Consider the $3\times 5$ array a3by5 created below.

In [15]:
np.random.seed(42) # This guarantees the code will generate the same set of random numbers whenever executed
a3by5 = np.random.random((3,5))
a3by5

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497]])

Flatten it into a list, sort the list and print it.


In [16]:
flat=np.sort(np.ndarray.flatten(a3by5))

print(flat)

[0.02058449 0.05808361 0.15599452 0.15601864 0.18182497 0.21233911
 0.37454012 0.59865848 0.60111501 0.70807258 0.73199394 0.83244264
 0.86617615 0.95071431 0.96990985]


## Exercise 5.

Consider the arrays x, y and z below.

In [17]:
x = np.array([-4, -3, -2, -1, 1, 2, 3, 4])
y = np.array([-3, -2, -1, 0, 1, 2, 3])
z = np.array([0, 0, 0, 0])
print(x)
print(y)
print(z)

[-4 -3 -2 -1  1  2  3  4]
[-3 -2 -1  0  1  2  3]
[0 0 0 0]


**1**. Write some code to test whether 
* at least one of the elements in the array is non-zero;
* all of the elements in the array are non-zero;
* at least one of the elements in the array is equal to zero;  

and apply it to each of the three arrays.

2. Add 5 to every positive entry in each array.

In [18]:
print(np.any(x))
print(np.any(y))
print(np.any(z))

True
True
False


now test all of the elements in the array are non-zero;

In [19]:
print(np.alltrue(x))
print(np.alltrue(y))
print(np.alltrue(z))

True
False
False


* at least one of the elements in the array is equal to zero;  


In [20]:
print(np.any(x==0))
print(np.any(y==0))
print(np.any(z==0))

False
True
True


In [21]:
for i in range(len(x)):
  if x[i]>0:
    x[i] +=5
   
    

In [22]:
for i in range(len(y)):
  if y[i]>0:
    y[i] +=5


In [23]:
for i in range(len(z)):
  if z[i]>0:
    z[i] +=5


In [24]:
print(x)
print(y)
print(z)

[-4 -3 -2 -1  6  7  8  9]
[-3 -2 -1  0  6  7  8]
[0 0 0 0]


## Exercise 6

Consider the Pauli matrices defined below.

$$
\left(
\begin{matrix}
0 & 1 \\
1 & 0
\end{matrix}
\right),
\left(
\begin{matrix}
0 & -i \\
i & 0
\end{matrix}
\right),
\left(
\begin{matrix}
1 & 0 \\
0 & -1
\end{matrix}
\right)
$$

1. Verify that they are traceless
2. Verify that they all have determinants -1.
3. Verify that they are Hermitian.
4. Verify that they are unitary.
5. Verify the SU(2) algebra, i.e., the commutation relations among the Pauli matrices. If you don't remember the formulas, derive them.


In [25]:
sigX = np.matrix([[0+0j,1+0j],[1+0j,0+0j]])
sigY = np.matrix([[0+0j,0-1j],[0+1j,0+0j]])
sigZ = np.matrix([[1+0j,0+0j],[0+0j,-1+0j]])
print(sigX) 
print(sigY)
print(sigZ)

[[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]
[[ 1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]


In [26]:
print(np.trace(sigX))
print(np.trace(sigY))
print(np.trace(sigZ))

0j
0j
0j


In [27]:
print(np.linalg.det(sigX))
print(np.linalg.det(sigY))
print(np.linalg.det(sigZ))

(-1+0j)
(-1+0j)
(-1+0j)


now let's get the hermitian of it's matrix (conjecgate trsnpose and they are gonna look the same as the orgingal matrix meaning that pauli matrices are hermitan)

In [28]:
print(sigX.getH)
print(sigY.getH)
print(sigZ.getH)

<bound method matrix.H of matrix([[0.+0.j, 1.+0.j],
        [1.+0.j, 0.+0.j]])>
<bound method matrix.H of matrix([[0.+0.j, 0.-1.j],
        [0.+1.j, 0.+0.j]])>
<bound method matrix.H of matrix([[ 1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]])>


to check they are unitary (if we multiply the the matrix by it's conjegat transpose we must get identity matrix) since they are hermitian(the inverse transpose is the same as the matrix itsel so it's enough to get the square of every matrix and check that it's gonna equal identity)

In [29]:
print(np.dot(sigX,sigX))
print(np.dot(sigY,sigY))
print(np.dot(sigZ,sigZ))
print(np.identity(2)==np.dot(sigX,sigX))
print(np.identity(2)==np.dot(sigY,sigY))
print(np.identity(2)==np.dot(sigZ,sigZ))


[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


now we check the SU2 comutation relation which is cyclic relation with the result being the missing matrix multiplied by complex (2i) (we cycle clockwise (xy then yz then zx)

In [30]:
print(np.dot(sigX,sigY)-np.dot(sigY,sigX)==2*(0+1j)*sigZ)
print(np.dot(sigY,sigZ)-np.dot(sigZ,sigY)==2*(0+1j)*sigX)
print(np.dot(sigZ,sigX)-np.dot(sigX,sigZ)==2*(0+1j)*sigY)

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


## Exercise 7




```
# This is formatted as code
```

Store the vector $(1,2,3)$ in a numpy array: first as a row vector, then as a column vector. Then compute the dot product of these two vectors.

In [31]:
c=np.array([1,2,3])
d=np.array([[1],[2],[3]])
print(np.dot(c,d))



[14]


## Exercise 8

Create the integer matrices
$$
x = \left(
\begin{matrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 
\end{matrix}
\right)
,
y = \left(
\begin{matrix}
1 & 2 & 3  \\
4 & 5 & 6  \\
7 & 8 & 9 \\
10 & 11 & 12 
\end{matrix}
\right).
$$
Describe each matrix, i.e., find its shape, size and dimensions. Print the element located in row 3 column 2 in each case. Then find the matrix products $x\cdot y$ and $y \cdot x$. Find the minimum and maximum entry in $x$. Then find the minimum entry in each column of $x$. Then find the average and the median entry in $x$.

In [56]:
matx=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
maty=np.matrix([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matx.shape)
print(maty.shape)
print(matx.size)
print(maty.size)
print(matx.ndim)
print(maty.ndim)
print(matx[2,1])
print(maty[2,1])
print(np.dot(matx,maty))
print(np.dot(maty,matx))
print(np.max(matx))
print(np.max(maty))
print(np.min(matx))
print(np.min(maty))
print(np.min(matx[:,0]))
print(np.min(matx[:,1]))
print(np.min(matx[:,2]))
print(np.min(matx[:,3]))
print(np.average(matx))
print(np.ma.median(matx))



(3, 4)
(4, 3)
12
12
2
2
10
8
[[ 70  80  90]
 [158 184 210]
 [246 288 330]]
[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]
 [173 206 239 272]]
12
12
1
1
1
2
3
4
6.5
[[ 2.  1.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]]


## Exercise 9

Construct the square matrix 
$$
{\mathbf x} = \left(
\begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{matrix}
\right).
$$
Create a new matrix obtained as follows: add $-1$ to the entries in the first column, $0$ to those in the middle column and $+1$ to the entries in the last column. Find the transpose $x^T$ of the matrix $x$. Calculate the determinant of $x$. Calculate the trace of $x$. Get the three elements in the main diagonal. Get the two elements in each of the shorter diagonals - the one above and the one below the main diagonal. Find the rank of the matrix. Find the three eigenvalues $\lambda_i$. Verify explicitly that they are solutions to the characteristic equation 
$$
\det ({\mathbf x} - \lambda_i {\mathbf 1} ) = 0.
$$

In [115]:
matrixx=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.matrix.transpose(matrixx))
print(np.linalg.det(matrixx))
print(np.trace(matrixx))
print(np.diag(matrixx))
print(matrixx[0,2],matrixx[2,0])
print(np.linalg.matrix_rank(matrixx))
print(np.linalg.eig(np.matrix([[1,2,3],[4,5,6],[7,8,9]])))

print(np.linalg.det(matrixx-np.matrix([[-1.30367773e-15,0,0],[0, -1.11684397e+00 ,0],[0,0,1.61168440e+01]])))





[[1 4 7]
 [2 5 8]
 [3 6 9]]
0.0
15
[1 5 9]
3 7
2
(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), matrix([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))
16.948404323169203
